### ISSUE TITLE
Youtube or Spotify integrations

### ISSUE THREAD

**Issue by GrubbyGroo** [icosa-foundation/open-brush#596] opened 2023-12-12 03:03 UTC
If possible, I wouild love to be able to use youtube or spotify within the game, for both just listening and also with the music reactive brushes. I don't know if its possible, but would love to see it if its doable.

**Comment by andybak** [comment] 2024-02-28 14:55
This is essentially a duplicate of #622 as that would be the only real way to do this. Also - it's Quest/standalone specific because as mentioned on #622 - you can already pretty much do this on PC.

**Closed by andybak** 2024-02-28 14:55 UTC
Labels: feature request
